name: keepbooks
version: '0.1.0.0'
synopsis: Keep your books like a pro!
category: Web
author: Philipp Middendorf
maintainer: middendorf@plapadoo.de
copyright: plapadoo UG (haftungsbeschränkt) 2017
license: BSD3
github: plapadoo/keepbooks
extra-source-files:
- README.md
default-extensions:
- OverloadedStrings
- NoImplicitPrelude
ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -Wall
dependencies:
- base
- filepath
- directory
- time
- unix
- optparse-applicative
executables:
  keepbooks:
    main: Main.hs
    source-dirs: app
